[[redirects]]
  from = "/interop-legacy-java-with-clojure"
  to = "/blog/2019/01/31/interop-legacy-java-with-clojure.html"

[[redirects]]
  from = "/recap-2018"
  to = "/blog/2019/01/02/recap-2018.html"