[build]
# This assumes that the Zola site is in a docs folder. If it isn't, you don't need
# to have a `base` variable but you do need the `publish` and `command` variables.
#base    = "."
publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.13.0"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

# Migration: ??? -> Middleman

[[redirects]]
  from = "/interop-legacy-java-with-clojure"
  to = "/blog/2019/01/31/interop-legacy-java-with-clojure.html"

[[redirects]]
  from = "/recap-2018"
  to = "/blog/2019/01/02/recap-2018.html"

[[redirects]]
  from = "/never-write-for-loops.html"
  to = "/blog/2016/11/17/you-probably-dont-need-for-loops.html"

# Migration: Middleman -> Zola

# 2016 (9)

[[redirects]]
  from = "/blog/2016/01/27/pyglet-game-under-30-mins"
  to = "/blog/pyglet-game-under-30-mins"

[[redirects]]
  from = "/blog/2016/01/27/wake-up-2-hrs-earlier"
  to = "/blog/wake-up-2-hrs-earlier"

[[redirects]]
  from = "/blog/2016/02/18/flask-for-new-dev"
  to = "/blog/flask-for-new-dev"

[[redirects]]
  from = "/blog/2016/02/25/truth-testing"
  to = "/blog/truth-testing"

[[redirects]]
  from = "/blog/practical-boolean-operators"
  to = "/blog/practical-boolean-operators"

[[redirects]]
  from = "/blog/2016/03/10/first-hackathon"
  to = "/blog/first-hackathon"

[[redirects]]
  from = "/blog/2016/03/26/twitter-scraper-1"
  to = "/blog/twitter-scraper-1"

[[redirects]]
  from = "/blog/2016/04/09/twitter-scraper-2"
  to = "/blog/twitter-scraper-2"

[[redirects]]
  from = "/blog/2016/11/17/you-probably-dont-need-for-loops"
  to = "/blog/you-probably-dont-need-for-loops"

# 2017 (6)

[[redirects]]
  from = "/blog/2017/01/04/40-books-in-2016"
  to = "/blog/40-books-in-2016"

[[redirects]]
  from = "/blog/2017/01/07/generator-the-basics"
  to = "/blog/generator-the-basics"

[[redirects]]
  from = "/blog/2017/02/18/closures-bind-late"
  to = "/blog/closures-bind-late"

[[redirects]]
  from = "/blog/2017/02/20/getting-started-python-internals"
  to = "/blog/getting-started-python-internals"

[[redirects]]
  from = "/blog/2017/09/23/python36-descriptors"
  to = "/blog/python36-descriptors"

[[redirects]]
  from = "/blog/2017/11/02/composing-namedtuple"
  to = "/blog/composing-namedtuple"

# 2018 (3)

[[redirects]]
  from = "/blog/2018/04/02/just-write-the-code"
  to = "/blog/just-write-the-code"

[[redirects]]
  from = "/blog/2018/04/24/study-group-at-work"
  to = "/blog/study-group-at-work"

[[redirects]]
  from = "/blog/2018/04/30/decode-phone-number"
  to = "/blog/decode-phone-number"

# 2019 (9)

[[redirects]]
  from = "/blog/2019/01/02/recap-2018"
  to = "/blog/recap-2018"

[[redirects]]
  from = "/blog/2019/01/31/interop-legacy-java-with-clojure"
  to = "/blog/interop-legacy-java-with-clojure"

[[redirects]]
  from = "/blog/2019/02/02/tachyons-review"
  to = "/blog/tachyons-review"

[[redirects]]
  from = "/blog/2019/02/09/clojure-inspect"
  to = "/blog/clojure-inspect"

[[redirects]]
  from = "/blog/2019/08/08/how-i-built-bex"
  to = "/blog/how-i-built-bex"

[[redirects]]
  from = "/blog/2019/08/13/re-frame-effects-vs-coeffects"
  to = "/blog/re-frame-effects-vs-coeffects"

[[redirects]]
  from = "/blog/2019/10/17/domain-exploring-with-spec"
  to = "/blog/domain-exploring-with-spec"

[[redirects]]
  from = "/blog/2019/10/24/my-core-values"
  to = "/blog/my-core-values"

[[redirects]]
  from = "/blog/2019/11/20/think-rationally-talk-emotionally"
  to = "/blog/think-rationally-talk-emotionally"

# 2020 (1 so far)

[[redirects]]
  from = "/blog/2020/04/06/from-vim-to-emacs"
  to = "/blog/from-vim-to-emacs"

# Other redirects

[[redirects]]
  from = "/about"
  to = "/"
